const test_searchResults = {
  results: [
    {
      "listing_id": 1,
      "type": "swap",
      "title": "GLC",
      "description": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
      "image_url": "http://dummyimage.com/149x100.png/dddddd/000000",
      "user_id": "gmordey0@tiny.cc",
      "user_avatar_url": "http://dummyimage.com/212x100.png/ff4444/ffffff",
      "distance": 2.889,
      "zip_code": "78702",
      "lat": 30.26,
      "lng": -97.71,
      "state": "CA",
      "city": "San Diego"
    },
    {
      "listing_id": 2,
      "type": "favor",
      "title": "Liberty",
      "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
      "image_url": "http://dummyimage.com/223x100.png/5fa2dd/ffffff",
      "user_id": "nunthank1@wikimedia.org",
      "user_avatar_url": "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
      "distance": 2.325,
      "zip_code": "78704",
      "lat": 30.24,
      "lng": -97.76,
      "state": "CA",
      "city": "Los Angeles"
    },
    {
      "listing_id": 3,
      "type": "favor",
      "title": "Tacoma",
      "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
      "image_url": "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
      "user_id": "mlaguerre2@wunderground.com",
      "user_avatar_url": "http://dummyimage.com/208x100.png/dddddd/000000",
      "distance": 0.748,
      "state": "CA",
      "city": "San Diego",
      "zip_code": "78708",
      "lat": 30.26,
      "lng": -97.73,
    },
    {
      "listing_id": 4,
      "type": "swap",
      "title": "LS",
      "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
      "image_url": "http://dummyimage.com/132x100.png/cc0000/ffffff",
      "user_id": "dgaisford3@ibm.com",
      "user_avatar_url": "http://dummyimage.com/170x100.png/cc0000/ffffff",
      "state": "CA",
      "city": "San Diego",
      "zip_code": "78741",
      "lat": 30.23,
      "lng": -97.71,
      "distance": 3.256,
    },
    {
      "listing_id": 5,
      "type": "swap",
      "title": "Safari",
      "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
      "image_url": "http://dummyimage.com/241x100.png/5fa2dd/ffffff",
      "user_id": "mdoel4@engadget.com",
      "user_avatar_url": "http://dummyimage.com/102x100.png/dddddd/000000",
      "state": "CA",
      "city": "Sacramento",
      "zip_code": "78742",
      "lat": 30.2406,
      "lng": -97.6602,
      "distance": 7.6,
    },
    {
      "listing_id": 6,
      "type": "swap",
      "title": "Yukon XL 2500",
      "description": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
      "image_url": "http://dummyimage.com/146x100.png/cc0000/ffffff",
      "user_id": "mbridewell5@multiply.com",
      "user_avatar_url": "http://dummyimage.com/183x100.png/5fa2dd/ffffff",
      "zip_code": "78759",
      "distance": 14.194,
      "lat": 30.23,
      "lng": -97.71,
      "state": "CA",
      "city": "Sacramento"
    },
    {
      "listing_id": 7,
      "type": "favor",
      "title": "QX",
      "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
      "image_url": "http://dummyimage.com/239x100.png/ff4444/ffffff",
      "user_id": "bhousden6@dedecms.com",
      "user_avatar_url": "http://dummyimage.com/250x100.png/ff4444/ffffff",
      "zip_code": "78759",
      "distance": 14.194,
      "lat": 30.23,
      "lng": -97.71, "state": "CA",
      "city": "Los Angeles"
    },
    {
      "listing_id": 8,
      "type": "swap",
      "title": "Silverado",
      "description": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
      "image_url": "http://dummyimage.com/197x100.png/dddddd/000000",
      "user_id": "etunny7@jugem.jp",
      "user_avatar_url": "http://dummyimage.com/235x100.png/dddddd/000000",
      "distance": 11.417,
      "zip_code": "78708",
      "lat": 30.26,
      "lng": -97.73,
      "state": "CA",
      "city": "Los Angeles"
    },
    {
      "listing_id": 9,
      "type": "favor",
      "title": "sittingchair2",
      "description": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      "image_url": "http://dummyimage.com/117x100.png/ff4444/ffffff",
      "user_id": "hcheine8@timesonline.co.uk",
      "user_avatar_url": "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
      "distance": 14.728,
      "zip_code": "78704",
      "lat": 30.24,
      "lng": -97.76,
      "state": "CA",
      "city": "Sunnyvale"
    },
    {
      "listing_id": 10,
      "type": "swap",
      "title": "hair chair",
      "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
      "image_url": "http://dummyimage.com/212x100.png/5fa2dd/ffffff",
      "user_id": "ldevoy9@aboutads.info",
      "user_avatar_url": "http://dummyimage.com/192x100.png/dddddd/000000",
      "distance": 13.325,
      "zip_code": "78702",
      "lat": 30.26,
      "lng": -97.71,
      "state": "CA",
      "city": "Inglewood",
    }
  ]
};

export default test_searchResults;